services:
    WowApps\PackagistBundle\Service\ApiProvider:
        public: false
    WowApps\PackagistBundle\Service\Packagist:
        arguments: ['@WowApps\PackagistBundle\Service\ApiProvider']
        public: false
    wowapps.packagist:
        alias: WowApps\PackagistBundle\Service\Packagist
        public: true
